spring.application.name=gestionconges

# Connexion à PostgreSQL (Le "Frigo")
spring.datasource.url=jdbc:postgresql://localhost:5432/hr_management
spring.datasource.username=postgres
spring.datasource.password=0000

# Configuration automatique des tables
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# ????? ?????? ????? ??????? ?? ????? ???? (??? Oracle ?? Jenkins)
server.port=8081

# ????? ?????? ??????? ?? ??????? ??? ????
server.error.include-message=always

# ????? ??????? ????? ?? Open-In-View
spring.jpa.open-in-view=false